"""initial sqlite schema

Revision ID: 1f9d066a88d7
Revises: 
Create Date: 2026-08-13 21:14:19.992611
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '1f9d066a88d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('pmid', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint(
        "event IN ('search', 'open', 'error', 'ncbi', 'translate', 'subscription')",
        name='ck_audit_logs_event',
    ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_event', ['event'], unique=False)
        batch_op.create_index('ix_audit_logs_telegram_user_id', ['telegram_user_id'], unique=False)

    op.create_table('translation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pmid', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.Text(), nullable=False),
    sa.Column('text_ru', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('title', 'abstract', 'fulltext')", name='ck_translation_cache_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pmid', 'kind', 'source_hash', name='uq_translation_cache_key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_user_id'), ['telegram_user_id'], unique=True)

    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pmid', sa.Text(), nullable=False),
    sa.Column('title_en', sa.Text(), nullable=False),
    sa.Column('title_ru', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pmid', name='uq_favorites_user_pmid')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pmid', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(body) <= 2000', name='ck_notes_body_len'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pmid', name='uq_notes_user_pmid')
    )
    op.create_table('searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('list_chat_id', sa.Integer(), nullable=True),
    sa.Column('list_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("domain IN ('sport', 'medicine', 'other')", name='ck_searches_domain'),
    sa.CheckConstraint('length(query_text) > 0', name='ck_searches_query_text'),
    sa.CheckConstraint('page >= 1', name='ck_searches_page'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_searches_user_id'), ['user_id'], unique=True)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("domain IN ('sport', 'medicine', 'other')", name='ck_subscriptions_domain'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'domain', 'query_text', name='uq_subscriptions_user_query')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('pmid', sa.Text(), nullable=False),
    sa.Column('title_en', sa.Text(), nullable=False),
    sa.Column('title_ru', sa.Text(), nullable=True),
    sa.Column('date_label', sa.Text(), nullable=True),
    sa.Column('status_label', sa.Text(), nullable=True),
    sa.Column('integrity_label', sa.Text(), nullable=True),
    sa.Column('pub_type_label', sa.Text(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ondelete='CASCADE'),
    sa.CheckConstraint('position BETWEEN 1 AND 10', name='ck_search_results_position'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_id', 'pmid', name='uq_search_results_pmid'),
    sa.UniqueConstraint('search_id', 'position', name='uq_search_results_position')
    )
    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_results_pmid'), ['pmid'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_results_search_id'), ['search_id'], unique=False)

    op.create_table('subscription_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('pmid', sa.Text(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'pmid', name='uq_subscription_deliveries_pmid')
    )
    with op.batch_alter_table('subscription_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_deliveries_delivered_at'), ['delivered_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_deliveries_delivered_at'))

    op.drop_table('subscription_deliveries')
    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_results_search_id'))
        batch_op.drop_index(batch_op.f('ix_search_results_pmid'))

    op.drop_table('search_results')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_searches_user_id'))

    op.drop_table('searches')
    op.drop_table('notes')
    op.drop_table('favorites')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_user_id'))

    op.drop_table('users')
    op.drop_table('translation_cache')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_telegram_user_id')
        batch_op.drop_index('ix_audit_logs_event')
        batch_op.drop_index('ix_audit_logs_created_at')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
